apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentrag-ingress
  namespace: agentrag
spec:
  ingressClassName: nginx

  rules:
    - host: agentrag.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: agentrag-backend
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentrag-frontend
                port:
                  number: 80