apiVersion: v1
kind: Secret
metadata:
  name: agentrag-mysql-secret
  namespace: agentrag
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "agentrag"
  MYSQL_USER: "agentrag"
  MYSQL_PASSWORD: "root"