apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentrag-python
  namespace: agentrag
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: agentrag-python

  template:
    metadata:
      labels:
        app: agentrag-python

    spec:
      containers:
        - name: python
          image: maissamaalej3/agentrag-python:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: QDRANT_HOST
              value: "agentrag-qdrant"

            - name: QDRANT_PORT
              value: "6333"

            - name: QDRANT_COLLECTION
              value: "azure_docs"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "2Gi"
