apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentrag-python
  namespace: agentrag

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: agentrag-python

  template:
    metadata:
      labels:
        app: agentrag-python

    spec:
      containers:
        - name: python
          image: maissamaalej3/agentrag-python:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            # =========================
            # QDRANT
            # =========================
            - name: QDRANT_HOST
              value: "agentrag-qdrant"

            - name: QDRANT_PORT
              value: "6333"

            - name: QDRANT_COLLECTION
              value: "azure_docs"

            # =========================
            # EMBEDDINGS
            # =========================
            - name: EMBEDDING_MODEL
              value: "BAAI/bge-small-en-v1.5"

            - name: EMBEDDING_DIMENSION
              value: "384"

            # =========================
            # LLM
            # =========================
            - name: LLM_PROVIDER
              value: "ollama"

            - name: OLLAMA_MODEL
              value: "qwen2.5-coder:7b"

            - name: OLLAMA_JUDGE_MODEL
              value: "qwen2.5:7b-instruct"

            # =========================
            # DOCUMENTS
            # =========================
            - name: DOCUMENTS_PATH
              value: "data"

            # =========================
            # LANGSMITH
            # =========================
            - name: LANGSMITH_TRACING
              value: "true"

            - name: LANGSMITH_PROJECT
              value: "AgentRAG"

          # =========================
          # HEALTH CHECKS
          # =========================

          # Donne jusqu'à 5 minutes à FastAPI
          # pour charger le modèle au démarrage.
          startupProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60

          # Vérifie si le pod est prêt à recevoir
          # des requêtes.
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          # Vérifie que l'application reste fonctionnelle
          # après son démarrage.
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          # =========================
          # RESOURCES
          # =========================
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "2Gi"
